### ISSUE TITLE
Compatibility with Neo4j 4.x

### ISSUE THREAD

**Issue by nmervaillie** [mariussturm/graylog-plugin-output-neo4j#5]
The plugin uses the 1.4 Neo4j driver, which is not compatible with Neo4j 4.x.
It would be great to switch to the 2.x driver series, which support both Neo4j 3.5 and 4.x server. I think using the 1.x drivers does not make sense anymore, as Neo4j versions < 3.5 are not supported anymore.

Would a PR help here ?

**Comment by mariussturm** [comment]
@nmervaillie yes, sure! If you have a PR prepared feel free to submit it.

**Comment by nmervaillie** [comment]
Merged in https://github.com/mariussturm/graylog-plugin-output-neo4j/pull/6
